"""add user following to the db model

Revision ID: 16b8e322492f
Revises: f5a9cb9597e8
Create Date: 2021-07-31 18:35:17.230132

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '16b8e322492f'
down_revision = 'f5a9cb9597e8'
branch_labels = None
depends_on = None


# noinspection PyTypeChecker
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
                    sa.Column('followed_id', sa.Integer(), nullable=False),
                    sa.Column('follower_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('followed_id', 'follower_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
