"""add watchlist table

Revision ID: c64933c72bb6
Revises: 16b8e322492f
Create Date: 2021-08-01 15:20:14.573240

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c64933c72bb6'
down_revision = '16b8e322492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # noinspection PyTypeChecker
    op.create_table('watches',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('stock_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'stock_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watches')
    # ### end Alembic commands ###
