"""fix trade model

Revision ID: f5a9cb9597e8
Revises: 1da3e524a8fd
Create Date: 2021-07-29 18:02:30.025281

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f5a9cb9597e8'
down_revision = '1da3e524a8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('ticker', sa.String(length=5), nullable=True),
                    sa.Column('sector', sa.String(length=32), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('year_high', sa.Float(), nullable=True),
                    sa.Column('year_low', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=True)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    # noinspection PyTypeChecker
    op.create_table('trades',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('stock_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
